apiVersion: apps/v1
kind: Deployment 
metadata:
  name:  app-crm
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: app-crm  
  template:
    metadata: 
      labels:
        app: app-crm 
    spec:
      containers:
      - name:  app
        image: betolira/django-crm:v1
        ports:
        - containerPort: 8000
        

---
apiVersion: v1
kind: Service
metadata:
  name:  service-app
spec:
  selector:
    app:  app-crm
  ports:
  - port:  80
    targetPort: 8000
    nodePort: 30000
  type: NodePort   