version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/etc/prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  loki:
    image: grafana/loki:2.4.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/etc/loki

  promtail:
    image: grafana/promtail:2.4.1
    command: -config.file=/etc/promtail/config.yaml
    volumes:
      - /var/log:/var/log
      - ./promtail/config.yaml:/etc/promtail/config.yaml
             

volumes:
  prometheus_data:
  grafana_data:
  loki_data:
  promtail_data:
